### ISSUE TITLE
Geckolib is Incompatible with Sodium

### ISSUE THREAD

**Issue by matty45** [bernie-g/geckolib#26]
Here is the full log: https://paste.ee/p/sF3Gg

I dont think this is easily fixable due to how things are rendered but i hope it should not be too much of a hassle.

**Comment by CammiePone** [comment]
Can confirm this one. Tried with just GeckoLib, just Sodium, and both together in 1.16.3 (even though GeckoLib doesn't officially support 1.16.3), and the crash only shows up when GeckoLib is paired with Sodium. Same log as Matty. I'm gonna guess it has to do with GeckoLib's access widener for `renderCuboids()`, while Sodium is using `@Overwrite` on it. Idk how hard that would be to fix since `@Overwrite` itself is just a pain to do compatibility with.

I do have one idea though: try using an Accessor Mixin instead of an access widener. They can be used on both methods and variables, and should allow you to get access to `renderCuboids()` without needing an access widener and _might_ maintain some compatibility with Sodium.

**Comment by bernie-g** [comment]
This will be fixed in 3.0.0, which is currently in alpha. I have no plans to fix this for 2.0.0 as I don't want people using that anymore after 3.0.0 is fully released so till then I guess it'll have to be broken :/
