### ISSUE TITLE
Issues with Connector

### ISSUE THREAD

**Issue by NEFFLEAFF** [bernie-g/geckolib#492]
Connector is a way to play Fabric mods on Forge, but Fabric Geckolib's ItemRenderer system is making the Forge items with custom models become invisible due to this.

What's your opinion on multiloader? That could help fixing this issue, which Connector dev can't fix by their own.

**Comment by Tslat** [comment]
I'm not sure how multiloader would fix this, given that item renderers would still be registered the same way

This sounds more like a connector issue?

**Comment by parka27** [comment]
[Su5eD](https://github.com/Su5eD) commented [yesterday](https://github.com/Sinytra/Connector/issues/198#issuecomment-1708789360)
The issue comes down to Fabric geckolib overriding the vanilla ItemRenderer with its own system, which is not compatible with Forge's IClientItemExtensions interface. As a result, geckolib can never find the correct render for Forge items that use custom models and ends up skipping rendering altogether. Unfortunately, it is beyond our control.

The ideal solution would be for geckolib to use a multiloader layout with shared code so the loader-specific versions can be interchanged without causing any problems. They have, however, made the decision to maintain 2 independent versions for each loader, and they likely had reasons for it. It might be worth asking about their opinion on multiloader, but it's certainly something we can't force them to do if they don't want to.

that's what the creator of sinytra (connector) said sorry, if it's too much text, I like your mobs men

**Comment by Tslat** [comment]
Ah I see

It is indeed a Geckolib issue
But it's not a simple one to deal with

I'll add to the list of things to look at

**Comment by Tslat** [comment]
@NEFFLEAFF are you in the Geckolib Discord?

**Comment by parka27** [comment]
de igual forma gracias por escucharnos

**Comment by NEFFLEAFF** [comment]
No, I'm not in the Geckolib Discord

**Comment by Tslat** [comment]
The only way to fix this would be to change how geckolib handles its itemrenderers, which would be a __downgrade__ of functionality, and also a breaking change
Given that Connector is already unstable with many, many mods, I'm not inclined to deal with this at the current time
